openapi: 3.0.0
info:
  title: Campus Booster API
  description: Private API for Campus Booster
  version: 1.0
servers:
  - url: /
    description: Production
  - url: /api/v1
    description: Development
paths:
  /auth/login:
    post:
      summary: Authenticate.
      description: Authenticate to Campus Booster with Azure ID
      consumes:
        - application/json
      produces:
        - application/json
      parameters:
        - name: azureId
          in: body
          description: Azure ID of user
          required: true
          type: string
          default: null
      responses:
        - 200:
          schema:
            $ref: '#/definitions/User'
        - 400:
          $ref: '#/responses/BadRequest'
        - 404:
          $ref: '#/responses/NotFound'
        - 500:
          $ref: '#/responses/Internal'  
  /users:
    get:
      summary: Returns a list of users.
      description: Optional extended description in CommonMark or HTML.
      responses:
        200:
          schema:
            $ref: '#/definitions/User'
        400:
          $ref: '#/responses/BadRequest'
        401:
          $ref: '#/responses/Unauthorized'
        404:
          $ref: '#/responses/NotFound'
        500:
          $ref: '#/responses/Internal' 
components:
  schemas:
    User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name
responses:
  NotFound:
    description: NotFound
    schema:
      $ref: '#/definitions/Error'
  BadRequest:
    description: Bad Request
    schema:
      type: string
  Unauthorized:
    description: Unauthorized
    schema:
      $ref: '#/definitions/Response'
  Internal:
    description: Internal
    schema:
      $ref: '#/definitions/Response'
definitions:
  Error:
    type: object
    properties:
      code:
        type: string
      message:
        type: string
    required:
      - code
      - message
  Response: 
    type: string
  User:
      type: object
      properties:
        id:
          type: integer
          format: int64
        name:
          type: string
      required:
        - id
        - name