version: "3.4"
services:
  postgres:
    build: "."
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=campusboosteradmin
    ports:
      - "5432:5432"
